version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: depcsuite
      MYSQL_DATABASE: depcsuite
      MYSQL_USER: depcsuite_user
      MYSQL_PASSWORD: depcsuite_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
